# Generated by Django 4.2.1 on 2023-05-10 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaktabMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='')),
                ('sarlavha', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=60)),
                ('bepul', models.BooleanField(default=False)),
                ('rasm', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Murojat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=15)),
                ('sarlavha', models.CharField(max_length=60)),
                ('xabar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Oqituvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=60)),
                ('fan', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=60)),
                ('matn', models.TextField()),
                ('rasm', models.FileField(upload_to='')),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bosqich', models.PositiveSmallIntegerField()),
                ('rang', models.CharField(max_length=20)),
                ('kurator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.oqituvchi')),
            ],
        ),
        migrations.CreateModel(
            name='Reyting_daftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chorak_1', models.PositiveSmallIntegerField()),
                ('chorak_2', models.PositiveSmallIntegerField()),
                ('chorak_3', models.PositiveSmallIntegerField()),
                ('chorak_4', models.PositiveSmallIntegerField()),
                ('yillik', models.PositiveSmallIntegerField()),
                ('imtihon', models.PositiveSmallIntegerField()),
                ('natija', models.CharField(max_length=50)),
                ('oquv_yili', models.CharField(max_length=20)),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.oquvchi')),
            ],
        ),
        migrations.AddField(
            model_name='oquvchi',
            name='sinf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.sinf'),
        ),
    ]
