# Generated by Django 4.2.1 on 2023-05-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_fanlar_sinf_fan_alter_oqituvchi_fan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinf',
            name='id_sinf',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
