# Generated by Django 4.2.1 on 2023-05-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_sinf_id_sinf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oqituvchi',
            name='fan',
        ),
        migrations.AddField(
            model_name='oqituvchi',
            name='fan',
            field=models.ManyToManyField(to='asosiy.fanlar'),
        ),
    ]
